#include "raylib.h"
#include "stdio.h"
#include "../app.h"
#include "stats.h"
#include "table.h"
#include "../theme.h"
#include "../../ui/ui.h"

void draw_time_tab(void *ctx, Rectangle area) {
  int fontSize = 20 * ui_scale();
  int yShift = 0;

  StatsTabCtx *s = ctx;
  SolveEntry *solves = s->solves;
  int i = s->current;
  SolveEntry currentSolve = solves[i];

  float time = currentSolve.plus2 ? currentSolve.time + 2.0 : currentSolve.time;
  const char* tt = currentSolve.dnf ?
    TextFormat("%.2f (DNF)", time) :
    TextFormat("%.2f", time);
  
  yShift += 120;

  DrawText(
    currentSolve.timestamp,
    area.x,
    area.y + yShift,
    fontSize - 8,
    Fade(COLOR_TEXT, 0.8)
  );

  yShift += 50;

  DrawText(
    tt,
    area.x,
    area.y + yShift,
    fontSize + 15,
    currentSolve.dnf ? COLOR_DESTRUCTIVE : COLOR_TEXT
  );

  DrawText(
    currentSolve.plus2 ? "(+2 Penalty)" : "(No +2)",
    area.x + MeasureText(tt, fontSize) + 100,
    area.y + yShift + 20,
    fontSize - 10,
    currentSolve.plus2 ? ORANGE : COLOR_TEXT
  );

  yShift += 70;

  DrawText(
    TextFormat("Scramble: %s", currentSolve.scramble),
    area.x,
    area.y + yShift,
    fontSize - 5,
    COLOR_TEXT
  );

  yShift += 60;

  if (s->copied && (GetTime() - s->copiedTime > 1.0)) {
    s->copied = 0;
  }

  if (ui_button((Rectangle){area.x, area.y + yShift, 300, 60}, s->copied ? "Solve details copied!" : "Copy solve details", COLOR_BG, COLOR_TEXT, COLOR_ACCENT, COLOR_ACTIVE, false) && !s->copied) {
    s->copied = 1;
    s->copiedTime = GetTime();

    const char* clipboardText;

    if (currentSolve.dnf) {
      clipboardText = TextFormat(
        "-- Generated by vempr/rubixed --\n\n"
        "Date: %s\n"
        "Time: %.2f (DNF)\n"
        "Penalty: %s\n"
        "Scramble: %s\n",
        time,
        currentSolve.plus2 ? "+2" : "None",
        currentSolve.scramble,
        currentSolve.timestamp
      );
    } else {
      clipboardText = TextFormat(
        "-- Generated by vempr/rubixed --\n\n"
        "Date: %s\n"
        "Time: %.2f\n"
        "Penalty: %s\n"
        "Scramble: %s\n",
        currentSolve.timestamp,
        time,
        currentSolve.plus2 ? "+2" : "None",
        currentSolve.scramble
      );
    }

    SetClipboardText(clipboardText);
  }
}

void draw_ao5_tab(void *ctx, Rectangle area) {
  int fontSize = 20 * ui_scale();
  int yShift = 0;

  StatsTabCtx *s = ctx;
  SolveEntry *solves = s->solves;
  int i = s->current;
  SolveEntry lastSolve = solves[i];

  float ao5 = compute_average(solves, i, 5);

  char ao5Buffer[32];
  if (ao5 < -1.5f) strcpy(ao5Buffer, "Not enough solves");
  else if (ao5 < -0.5f) strcpy(ao5Buffer, "DNF");
  else snprintf(ao5Buffer, sizeof(ao5Buffer), "%.2f", ao5);
  
  yShift += 120;

  DrawText(
    TextFormat("Last solve at: %s", lastSolve.timestamp),
    area.x,
    area.y + yShift,
    fontSize - 8,
    Fade(COLOR_TEXT, 0.8)
  );

  yShift += 50;

  Color ao5Color = COLOR_TEXT;
  if (ao5 < -0.5f && ao5 > -1.5f) ao5Color = COLOR_DESTRUCTIVE;

  DrawText(
    TextFormat("AO5: %s", ao5Buffer),
    area.x,
    area.y + yShift,
    fontSize + 15,
    ao5Color
  );

  yShift += 70;

  float times[5];
  int indices[5];
  int best = -1, worst = -1;

  if (ao5 >= 0.0f || (ao5 < -0.5f && ao5 > -1.5f)) {
    for (int j = 0; j < 5; j++) {
      int idx = i - (4 - j);
      indices[j] = idx;

      if (solves[idx].dnf) {
        times[j] = __FLT_MAX__;
      } else {
        times[j] = solves[idx].plus2 ? solves[idx].time + 2.0f : solves[idx].time;
      }
    }

    float bestTime = __FLT_MAX__, worstTime = -__FLT_MAX__;

    for (int j = 0; j < 5; j++) {
      if (times[j] == __FLT_MAX__) continue;
      if (times[j] < bestTime) {
        bestTime = times[j]; best = j;
      } 
      if (times[j] > worstTime) {
        worstTime = times[j]; worst = j;
      }
    }

    char display[256] = "";
    char temp[32];

    for (int j = 0; j < 5; j++) {
      if (solves[indices[j]].dnf) {
        snprintf(temp, sizeof(temp), "DNF", times[j]);
      } else {
        if (j == best || j == worst) {
          snprintf(temp, sizeof(temp), "(%.2f)", times[j]);
        } else {
          snprintf(temp, sizeof(temp), "%.2f", times[j]);
        }
      }

      if (j > 0) strcat(display, "  ");
      strcat(display, temp);
    }

    DrawText(
      display,
      area.x,
      area.y + yShift,
      fontSize - 5,
      COLOR_TEXT
    );

    yShift += 60;
  }

  if (s->copied && (GetTime() - s->copiedTime > 1.0)) {
    s->copied = 0;
  }

  if (ui_button((Rectangle){area.x, area.y + yShift, 300, 60}, s->copied ? "Ao5 details copied!" : "Copy Ao5 details", COLOR_BG, COLOR_TEXT, COLOR_ACCENT, COLOR_ACTIVE, false) && !s->copied) {
    s->copied = 1;
    s->copiedTime = GetTime();

    if (ao5 < -1.5f) {
      const char* clipboardText = TextFormat(
        "-- Generated by vempr/rubixed --\n\n"
        "AO5: %s\n\n"
        "Not enough solves to calculate average.\n",
        ao5Buffer
      );

      SetClipboardText(clipboardText);

      return;
    }

    char temp[64];
    char headerLine[512] = "";
    char allSolves[4096] = "";

    for (int j = 0; j < 5; j++) {
      if (solves[indices[j]].dnf) {
        snprintf(temp, sizeof(temp), "DNF", times[j]);
      } else {
        if (j == best || j == worst) {
          snprintf(temp, sizeof(temp), "(%.2f)", times[j]);
        } else {
          snprintf(temp, sizeof(temp), "%.2f", times[j]);
        }
      }

      if (j > 0) strcat(headerLine, "  ");
      strcat(headerLine, temp);
    }

    for (int j = 0; j < 5; j++) {
      float time = solves[indices[j]].plus2 ? solves[indices[j]].time + 2.0 : solves[indices[j]].time;

      char solveDetail[512];
      if (solves[indices[j]].dnf) {
        snprintf(solveDetail, sizeof(solveDetail),
          "Date: %s\n"
          "Time: %.2f (DNF)\n"
          "Penalty: %s\n"
          "Scramble: %s\n",
          solves[indices[j]].timestamp,
          time,
          solves[indices[j]].plus2 ? "+2" : "None",
          solves[indices[j]].scramble
        );
      } else {
        snprintf(solveDetail, sizeof(solveDetail),
          "Date: %s\n"
          "Time: %.2f\n"
          "Penalty: %s\n"
          "Scramble: %s\n",
          solves[indices[j]].timestamp,
          time,
          solves[indices[j]].plus2 ? "+2" : "None",
          solves[indices[j]].scramble
        );
      }

      strcat(allSolves, solveDetail);
      if (j < 4) strcat(allSolves, "\n");
    }

    const char* clipboardText = TextFormat(
      "-- Generated by vempr/rubixed --\n\n"
      "%s\n"
      "AO5: %s\n\n"
      "%s",
      headerLine,
      ao5Buffer,
      allSolves
    );

    SetClipboardText(clipboardText);
  }
}

void draw_ao12_tab(void *ctx, Rectangle area) {
  int fontSize = 20 * ui_scale();
  int yShift = 0;

  StatsTabCtx *s = ctx;
  SolveEntry *solves = s->solves;
  int i = s->current;
  SolveEntry lastSolve = solves[i];

  float ao12 = compute_average(solves, i, 12);

  char ao12Buffer[32];
  if (ao12 < -1.5f) strcpy(ao12Buffer, "Not enough solves");
  else if (ao12 < -0.5f) strcpy(ao12Buffer, "DNF");
  else snprintf(ao12Buffer, sizeof(ao12Buffer), "%.2f", ao12);
  
  yShift += 120;

  DrawText(
    TextFormat("Last solve at: %s", lastSolve.timestamp),
    area.x,
    area.y + yShift,
    fontSize - 8,
    Fade(COLOR_TEXT, 0.8)
  );

  yShift += 50;

  Color ao12Color = COLOR_TEXT;
  if (ao12 < -0.5f && ao12 > -1.5f) ao12Color = COLOR_DESTRUCTIVE;

  DrawText(
    TextFormat("AO12: %s", ao12Buffer),
    area.x,
    area.y + yShift,
    fontSize + 15,
    ao12Color
  );

  yShift += 70;

  float times[12];
  int indices[12];
  int best = -1, worst = -1;

  if (ao12 >= 0.0f || (ao12 < -0.5f && ao12 > -1.5f)) {
    for (int j = 0; j < 12; j++) {
      int idx = i - (11 - j);
      indices[j] = idx;

      if (solves[idx].dnf) {
        times[j] = __FLT_MAX__;
      } else {
        times[j] = solves[idx].plus2 ? solves[idx].time + 2.0f : solves[idx].time;
      }
    }

    float bestTime = __FLT_MAX__, worstTime = -__FLT_MAX__;

    for (int j = 0; j < 12; j++) {
      if (times[j] == __FLT_MAX__) continue;
      if (times[j] < bestTime) {
        bestTime = times[j]; best = j;
      } 
      if (times[j] > worstTime) {
        worstTime = times[j]; worst = j;
      }
    }

    char display[256] = "";
    char temp[32];

    for (int j = 0; j < 12; j++) {
      if (solves[indices[j]].dnf) {
        snprintf(temp, sizeof(temp), "DNF", times[j]);
      } else {
        if (j == best || j == worst) {
          snprintf(temp, sizeof(temp), "(%.2f)", times[j]);
        } else {
          snprintf(temp, sizeof(temp), "%.2f", times[j]);
        }
      }

      if (j > 0) strcat(display, "  ");
      strcat(display, temp);
    }

    DrawText(
      display,
      area.x,
      area.y + yShift,
      fontSize - 5,
      COLOR_TEXT
    );

    yShift += 60;
  }

  if (s->copied && (GetTime() - s->copiedTime > 1.0)) {
    s->copied = 0;
  }

  if (ui_button((Rectangle){area.x, area.y + yShift, 300, 60}, s->copied ? "Ao12 details copied!" : "Copy Ao12 details", COLOR_BG, COLOR_TEXT, COLOR_ACCENT, COLOR_ACTIVE, false) && !s->copied) {
    s->copied = 1;
    s->copiedTime = GetTime();

    if (ao12 < -1.5f) {
      const char* clipboardText = TextFormat(
        "-- Generated by vempr/rubixed --\n\n"
        "AO12: %s\n\n"
        "Not enough solves to calculate average.\n",
        ao12Buffer
      );

      SetClipboardText(clipboardText);

      return;
    }

    char temp[64];
    char headerLine[512] = "";
    char allSolves[4096] = "";

    for (int j = 0; j < 12; j++) {
      if (solves[indices[j]].dnf) {
        snprintf(temp, sizeof(temp), "DNF", times[j]);
      } else {
        if (j == best || j == worst) {
          snprintf(temp, sizeof(temp), "(%.2f)", times[j]);
        } else {
          snprintf(temp, sizeof(temp), "%.2f", times[j]);
        }
      }

      if (j > 0) strcat(headerLine, "  ");
      strcat(headerLine, temp);
    }

    for (int j = 0; j < 12; j++) {
      float time = solves[indices[j]].plus2 ? solves[indices[j]].time + 2.0 : solves[indices[j]].time;

      char solveDetail[512];
      if (solves[indices[j]].dnf) {
        snprintf(solveDetail, sizeof(solveDetail),
          "Date: %s\n"
          "Time: %.2f (DNF)\n"
          "Penalty: %s\n"
          "Scramble: %s\n",
          solves[indices[j]].timestamp,
          time,
          solves[indices[j]].plus2 ? "+2" : "None",
          solves[indices[j]].scramble
        );
      } else {
        snprintf(solveDetail, sizeof(solveDetail),
          "Date: %s\n"
          "Time: %.2f\n"
          "Penalty: %s\n"
          "Scramble: %s\n",
          solves[indices[j]].timestamp,
          time,
          solves[indices[j]].plus2 ? "+2" : "None",
          solves[indices[j]].scramble
        );
      }

      strcat(allSolves, solveDetail);
      if (j < 4) strcat(allSolves, "\n");
    }

    const char* clipboardText = TextFormat(
      "-- Generated by vempr/rubixed --\n\n"
      "%s\n"
      "AO12: %s\n\n"
      "%s",
      headerLine,
      ao12Buffer,
      allSolves
    );

    SetClipboardText(clipboardText);
  }
}